# Generated by Django 4.2.1 on 2023-09-12 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True, verbose_name='Код подтверждения пользователя'),
        ),
    ]
